version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-23.11"
  commands:
      - mamba install -c conda-forge -c nodefaults pixi
      - pixi install -e dev
      - pixi run -e dev sphinx-build -M html docs/source $READTHEDOCS_OUTPUT/html/
