[workspace]
authors = ["macauwet <cauwet@isir.upmc.fr>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "ros_brian"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
paramecium = "python src/ros_standalone/paramecium.py"
briantenberg = "python src/ros_standalone/briantenberg.py"

[dependencies]
python = ">=3.11.12,<3.12"
catkin_pkg = ">=1.0.0,<2"
brian2 = ">=2.8.0.4,<3"
numpy = ">=1.26.4,<2"
ros-jazzy-desktop = ">=0.11.0,<0.12"
cmake = ">=4.0.1,<5"
make = ">=4.4.1,<5"
setuptools = ">=78.1.0,<79"
colcon-common-extensions = ">=0.3.0,<0.4"
jinja2 = ">=3.1.6,<4"

[pypi-dependencies]
brian-interface = { path = "./src/src/brian_interface" }

[feature.gz.dependencies]
ros-jazzy-ros-gz = ">=1.0.7,<2"
ros-jazzy-rqt-plot = ">=1.4.0,<2"
ros-jazzy-rviz2 = ">=14.1.7,<15"
ros-jazzy-rqt-gui = ">=1.6.0,<2"
ros-jazzy-rqt-common-plugins = ">=1.2.0,<2"
ros-jazzy-rqt-action = ">=2.2.0,<3"
ros-jazzy-rqt-image-view = ">=1.3.0,<2"
ros-jazzy-rqt-console = ">=2.2.1,<3"
matplotlib = ">=3.10.1,<4"
pyqtgraph = ">=0.13.7,<0.14"

[feature.dev.dependencies]
sphinx = ">=7.3.7,<8"
sphinx-rtd-theme = ">=2.0.0,<3"
sphinx-autodoc-typehints = ">=2.1,<3"
pytest = ">=8.3.5,<9"
myst-parser = ">=4.0.1,<5"

[environments]
dev = { features = ["dev", "gz"], solve-group = "default" }
gz = { features = ["gz"], solve-group = "default" }
