[workspace]
authors = ["macauwet <cauwet@isir.upmc.fr>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "ros_brian"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
paramecium = "python src/ros_standalone/examples/basic/paramecium.py"
briantenberg = "python src/ros_standalone/examples/basic/briantenberg.py"
jeffres_record = "python src/ros_standalone/examples/microphone/jeffres_record.py"
jeffres_micro = "python src/ros_standalone/examples/microphone/jeffres_micro.py"
jeffres = "python src/ros_standalone/examples/microphone/jeffres_audio.py"

colcon_recorder = "colcon build --packages-select turtleaudio"
source_robot = { cmd = ["source install/setup.bash"], depends-on = ["colcon_recorder"]}
robot_audio = { cmd = ["ros2 run turtleaudio audio_record"], depends-on = ["source_robot"]}

[dependencies]
python = ">=3.12.11,<3.13"
catkin_pkg = ">=1.0.0,<2"
brian2 = ">=2.9.0,<3"
numpy = ">=1.26.4,<2"
ros-jazzy-desktop = ">=0.11.0,<0.12"
cmake = ">=4.0.3,<5"
make = ">=4.4.1,<5"
setuptools = ">=80.9.0,<81"
colcon-common-extensions = ">=0.3.0,<0.4"
jinja2 = ">=3.1.6,<4"
ros-jazzy-rclcpp = ">=28.1.9,<29"
pip = ">=25.1.1,<26"

[pypi-dependencies]
brian-interface = { path = "./src/src/brian_interface" }

[feature.gz.dependencies]
ros-jazzy-ros-gz = ">=1.0.7,<2"
ros-jazzy-rqt-plot = ">=1.4.0,<2"
ros-jazzy-rviz2 = ">=14.1.7,<15"
ros-jazzy-rqt-gui = ">=1.6.0,<2"
ros-jazzy-rqt-common-plugins = ">=1.2.0,<2"
ros-jazzy-rqt-action = ">=2.2.0,<3"
ros-jazzy-rqt-image-view = ">=1.3.0,<2"
ros-jazzy-rqt-console = ">=2.2.1,<3"
matplotlib = ">=3.10.1,<4"
pyqtgraph = ">=0.13.7,<0.14"

[feature.dev.dependencies]
sphinx = ">=7.3.7,<8"
sphinx-rtd-theme = ">=2.0.0,<3"
sphinx-autodoc-typehints = ">=2.1,<3"
pytest = ">=8.3.5,<9"
myst-parser = ">=4.0.1,<5"

[feature.audio.dependencies]
python-sounddevice = ">=0.5.0,<0.6"
pulseaudio = ">=17.0,<18"
libcap = ">=2.75,<3"

[feature.audiorobot.dependencies]
python-sounddevice = ">=0.5.0,<0.6"
libcap = ">=2.71,<2.72.0a0"
ros-jazzy-nav2-bringup = "1.3.7"

[environments]
dev = { features = ["dev", "gz"], solve-group = "default" }
gz = { features = ["gz"], solve-group = "default" }
audio = { features = ["gz", "audio"], solve-group = "default"}
audiorobot = { features = ["audiorobot"], solve-group = "robot"}
