from brian2 import *
from brian2ros import *
from scipy.io import wavfile as wav

sample_rate = 48 * kHz
buffer_size = 128
defaultclock.dt = 1 / sample_rate
sound_speed = 300*metre/second

# Ears parameters
sigma_ear = .1
tau_ear = 1*ms
angular_speed = 2 * pi / second # 1 turn/second
max_delay = 0.62*ms 

# Coincidence detectors
num_neurons = 30
tau = 1*ms
sigma = .1

set_device('ros_standalone',directory="src/src/brian_project", debug=True)

# === Sound input from microphone ===
# The sound input is generated by a C++ code that uses PortAudio.
# The C++ code is compiled and linked to the Brian2 code using the
# `@implementation` decorator.

@implementation('cpp','//actual code in sound_from_mic.cpp',
                    sources=[os.path.abspath('src/ros_standalone/examples/microphone/sound_from_mic.cpp')],
                    headers=['"{}"'.format(os.path.abspath('src/ros_standalone/examples/microphone/sound_input.h'))],
                    libraries=['portaudio'],
                    define_macros=[('BUFFER_SIZE', buffer_size),
                                   ('SAMPLE_RATE', sample_rate/Hz)])
@check_units(t=second,side=1, result=1)
def get_sample(t,side):
    raise NotImplementedError('Use a C++-based code generation target.')

# Ears and sound motion around the head (constant angular speed)
eqs_ears = '''
dx/dt = (get_sample(t-delay,i)-x)/tau_ear+sigma_ear*(2./tau_ear)**.5*xi : 1 (unless refractory)
delay = distance*sin(theta) : second
distance : second # distance to the centre of the head in time units
dtheta/dt = angular_speed : radian
'''
ears = NeuronGroup(2, eqs_ears, threshold='x>1', reset='x = 0',
                   refractory=2.5*ms, name='ears', method='euler')
ears.distance = [-.5 * max_delay, .5 * max_delay]
traces = StateMonitor(ears, 'delay', record=True)
son = StateMonitor(ears, 'x', record=True)
eqs_neurons = '''
dv/dt = -v / tau + sigma * (2 / tau)**.5 * xi : 1
'''
neurons = NeuronGroup(num_neurons, eqs_neurons, threshold='v>1',
                      reset='v = 0', name='neurons', method='euler')

synapses = Synapses(ears, neurons, on_pre='v += .5')
synapses.connect()

synapses.delay['i==0'] = '(1.0*j)/(num_neurons-1)*1.1*max_delay'
synapses.delay['i==1'] = '(1.0*(num_neurons-j-1))/(num_neurons-1)*1.1*max_delay'

spikes = SpikeMonitor(neurons)
spikes_ears = SpikeMonitor(ears)
run(10000*second)
