from brian2 import *
from brian2ros import *
from scipy.io import wavfile as wav

set_device('ros_standalone',directory="src/src/brian_project", debug=True)

sample_rate = 48 * kHz
buffer_size = 16
defaultclock.dt = 1 / sample_rate

# Ears parameters
sigma_ear = .1
tau_ear = 0.5*ms
max_delay = 0.23*ms 

# Coincidence detectors
num_neurons = 30
tau = 0.5*ms
sigma = .1

# Thresholds
a = 0.1
p = 3.5
tau_thresh = 2*ms


# === Sound input from microphone ===
# The sound input is generated by a C++ code that uses PortAudio.
# The C++ code is compiled and linked to the Brian2 code using the
# `@implementation` decorator.

@implementation('cpp','//actual code in sound_from_mic.cpp',
                    sources=[os.path.abspath('src/ros_standalone/examples/microphone/sound_from_mic.cpp')],
                    headers=['"{}"'.format(os.path.abspath('src/ros_standalone/examples/microphone/sound_input.h'))],
                    libraries=['portaudio'],
                    define_macros=[('BUFFER_SIZE', buffer_size),
                                   ('SAMPLE_RATE', sample_rate/Hz)])
@check_units(t=second,side=1, result=1)
def get_sample(t,side):
    raise NotImplementedError('Use a C++-based code generation target.')

# Ears and sound motion around the head (constant angular speed)
eqs_ears = '''
dx/dt = (get_sample(t,i) - x)/tau_ear : 1 
dthresh/dt = (a * clip(x, 0, inf) - thresh) / tau_thresh : 1
'''

reset = '''
x = 0
thresh = p * thresh
'''
ears = NeuronGroup(2, eqs_ears, threshold='x>thresh and x>0.05',reset=reset,
                    name='ears', method='euler')
ears.thresh = [1, 1]

eqs_neurons = '''
dv/dt = -v / tau : 1
'''
neurons = NeuronGroup(num_neurons, eqs_neurons, threshold='v>1',
                      reset='v = 0', name='neurons', method='euler')

synapses = Synapses(ears, neurons, on_pre='v += .5')
synapses.connect()

synapses.delay['i==0'] = '(1.0*j)/(num_neurons-1)*1.1*max_delay'
synapses.delay['i==1'] = '(1.0*(num_neurons-j-1))/(num_neurons-1)*1.1*max_delay'

spikes = SpikeMonitor(neurons)
son = StateMonitor(ears, 'x', record=True)
th = StateMonitor(ears, 'thresh', record=True)

run(10000*second, report='text')

